import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";
import PageWrapper from "./components/PageWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        <div className="flex min-h-screen">
        <Sidebar></Sidebar>
        <Header></Header>
        <PageWrapper>
          {children}
        </PageWrapper>
        </div>
        {/* <main>{children}</main> */}
        </body>
    </html>
  );
}
